### ISSUE TITLE
[BUG] Server Crashes for Unknown Reason

### ISSUE THREAD

**Issue by Faun471** [IridiumLLC/IridiumSkyblock#206] opened 2020-08-08 22:21 UTC
**Describe the bug**
I believe this is when a player's island is calculating. I have never successfully pinpointed how and why it this exactly happens, but the issue needs to be brought to light.

**To Reproduce**
As stated before, I don't know what causes the problem I'm facing, as a result, I have no idea how to reproduce it. 
The issue happened when I used the command **/is update <player_name>** However, when I killed the server and started it again, I was able to update the player's island value using the same command.

**Logs**
https://hastebin.com/xojudanodu.md
https://hastebin.com/ocesanezid.md
https://hastebin.com/qumolawulu.md

I hope this can be resolved soon. Thanks!

-----------------------

**Server Details**
Paper version (as of writing of the original issue):  git-Paper-111 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Plugin version: 2.4.6
Maximum Ram: 6372 MB

**Comment by Seliba** [comment] 2020-08-09 21:36
I can' t reproduce this issue. You should upgrade to the latest version of Paper and try if the error still occurs

**Comment by Faun471** [comment] 2020-08-10 01:21
> I can't reproduce this issue. You should upgrade to the latest version of Paper and try if the error still occurs

Yeah, my method of reproducing the bug is unreliable. It's not consistent, sometimes updating a player's island value will work, sometimes it'll crash the server. I should have given our server details, sorry about that!

**Comment by IridiumLLC** [comment] 2020-08-13 17:16
Probabbly Fixed now since I recoded the island value system

**Closed by IridiumLLC** 2020-08-13 17:16 UTC
Labels: bug
