### ISSUE TITLE
[BUG] Could not pass event PlayerBucketEmptyEvent to IridiumSkyblock v2.4.6

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#188] opened 2020-07-23 20:15 UTC
When a player interact on your island with a bucket send this error on console

> [15:42:57 ERROR]: Could not pass event PlayerBucketEmptyEvent to IridiumSkyblock v2.4.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"4c7641d"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:179) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:152) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.ItemBucket.a(ItemBucket.java:89) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.ItemStack.a(ItemStack.java:236) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerInteractManager.useItem(PlayerInteractManager.java:371) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:734) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerBucketEmptyEvent.getBlock()Lorg/bukkit/block/Block;
at com.iridium.iridiumskyblock.listeners.PlayerBucketEmptyListener.onBucketEmpty(PlayerBucketEmptyListener.java:22) ~[?:?]
at sun.reflect.GeneratedMethodAccessor455.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"4c7641d"]
... 21 more

**Comment by IridiumLLC** [comment] 2020-07-23 21:48
duplicate of #180

**Closed by IridiumLLC** 2020-07-23 21:48 UTC
Labels: bug
