### ISSUE TITLE
[BUG] Console spam with netherwart farm

### ISSUE THREAD

**Issue by tommasobenatti** [IridiumLLC/IridiumSkyblock#523] opened 2021-01-18 03:10 UTC
**Describe the bug**
Do a netherwart farm like this one (https://cdn.discordapp.com/attachments/677967722839277600/800562288851419196/2021-01-18_04.08.10.png)

**To Reproduce**
1. Go to 'Create a netherwart farm'
2. Click on 'nothing'
3. Scroll down to 'nothing'
4. See error in console

**Console Error**
```
[03:05:16] [Server thread/WARN]: java.lang.IllegalArgumentException: Provided data is not of type org.bukkit.material.NetherWarts, found org.bukkit.material.Crops
[03:05:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.setData(CraftBlockState.java:116)
[03:05:16] [Server thread/WARN]: 	at com.iridium.iridiumskyblock.listeners.BlockGrowListener.onBlockGrow(BlockGrowListener.java:37)
[03:05:16] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor771.execute(Unknown Source)
[03:05:16] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[03:05:16] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[03:05:16] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:05:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[03:05:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1143)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.BlockNetherWart.tick(BlockNetherWart.java:36)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:584)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:1136)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1034)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:887)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1430)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:391)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1278)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1009)
[03:05:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[03:05:16] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Screenshots**
https://cdn.discordapp.com/attachments/677967722839277600/800562524063399956/unknown.png
https://cdn.discordapp.com/attachments/677967722839277600/800562288851419196/2021-01-18_04.08.10.png

**Comment by dlsf** [comment] 2021-02-02 12:39
Duplicate of #440

**Closed by dlsf** 2021-02-02 12:39 UTC
Labels: bug
