### ISSUE TITLE
[BUG] Spam message join when chest rollback

### ISSUE THREAD

**Issue by MrMathias154** [IridiumLLC/IridiumSkyblock#140] opened 2020-06-30 19:42 UTC
Sprint in a chest on hopper 

Video
https://dai.ly/x7ur12p

**Comment by IridiumLLC** [comment] 2020-06-30 20:37
This is most likely caused by an anticheat with antiphaze or something. Could you remove your anticheat temperately and confirm this? If removing the anticheat does fix it pm me on discord, if it doesnt let me know :)

**Comment by IridiumLLC** [comment] 2020-07-01 13:13
Should be fixed in latest commit

**Closed by IridiumLLC** 2020-07-01 13:13 UTC
Labels: bug
