### ISSUE TITLE
[BUG] spam error 

### ISSUE THREAD

**Issue by DExq123** [IridiumLLC/IridiumSkyblock#473] opened 2020-12-30 15:29 UTC
spam in the console and the server is stopped by lag

paperpigot 1.16.4
iridiumskyblock 2.6.5

[15:49:51] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@71c9458f on thread Craft Scheduler Thread - 1272, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$getIslands$0(IslandDataManager.java:25) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-325]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-325]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[15:49:51] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@364ae1bd on thread Craft Scheduler Thread - 1046, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:83) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$save$1(IslandDataManager.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-325]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-325]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[15:49:51] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@2721869a on thread Craft Scheduler Thread - 1272, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.getIslandViaId(IslandManager.java:204) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$getIslands$0(IslandDataManager.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-325]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-325]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1010)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1022)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:987)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.sqlite.core.DB.exec(DB.java:185)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:387)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:86)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$save$1(IslandDataManager.java:80)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:49:51] [Craft Scheduler Thread - 1046/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1010)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1022)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at org.sqlite.core.DB.execute(DB.java:861)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandManager.getIslandViaId(IslandManager.java:208)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$getIslands$0(IslandDataManager.java:33)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:49:51] [Craft Scheduler Thread - 1272/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:49:51] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@7ba805f9 on thread Craft Scheduler Thread - 1288, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:83) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$save$1(IslandDataManager.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-325]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-325]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1010)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1022)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.sqlite.core.DB.execute(DB.java:861)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:902)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:64)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:84)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$save$1(IslandDataManager.java:80)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:49:51] [Craft Scheduler Thread - 1288/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:49:51] [Craft Scheduler Thread - 1288/INFO]: [com.zaxxer.hikari.pool.ProxyLeakTask] Previously reported leaked connection org.sqlite.jdbc4.JDBC4Connection@7ba805f9 on thread Craft Scheduler Thread - 1288 was returned to the pool (unleaked)
[15:49:51] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@31321f06 on thread Craft Scheduler Thread - 1355, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:83) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$save$1(IslandDataManager.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-325]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-325]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by PeachesMLG** [comment] 2020-12-30 19:56
this is caused by a bug  thats been fixed
restart your server should fix it

**Comment by PeachesMLG** [comment] 2020-12-31 13:01
[13:35:03] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@44936fd7 on thread Craft Scheduler Thread - 8414, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.save(IslandDataManager.java:83) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandDataManager.lambda$save$1(IslandDataManager.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-353]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-353]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by PeachesMLG** [comment] 2021-01-13 11:24
Will be fixed in 3.0.0

**Closed by PeachesMLG** 2021-01-13 11:24 UTC
Labels: bug
