### ISSUE TITLE
Everyone can get "Back" item (It's Nether Star by default) from iridium's menus

### ISSUE THREAD

**Issue by Mohamad82Bz** [IridiumLLC/IridiumSkyblock#380] opened 2020-11-21 14:12 UTC
If you press "F" in for example /is top on "Back" item, it will duplicate it to your OffHand slot, Then you can close the inventory and get that Item from your OffHand. Generally, it should be an Ghost Item. **But It's Real!**

![image](https://user-images.githubusercontent.com/65306187/99879256-e9526980-2c20-11eb-8496-866074233252.png)

**Comment by Mohamad82Bz** [comment] 2020-11-21 19:57
**UPDATE**
It wasn't by pressing "F"!
Watch this video to understand: https://cdn.discordapp.com/attachments/592092308514537510/779787552231653446/2020-11-21_22-28-24.mkv

What they done: These two players opened their Island panel at the same time, then clicked Island Permissions at the same time and spam click those, then they can drop or get every single item in Island Permissions
It's not just Island permissions, same to other menus
These two people are in the same island

**Comment by IridiumLLC** [comment] 2020-11-22 17:55
Any errors in console?

**Comment by Mohamad82Bz** [comment] 2020-11-22 18:42
Nope

**Comment by dlsf** [comment] 2020-12-29 16:24
Are you sure that this is possible in Survival mode?

**Comment by Mohamad82Bz** [comment] 2020-12-31 12:42
I mentioned a video in a comment above. as you see there, those two players were in survival mode, and they dropped all contents of an irridium menu.

**Comment by BomBardyGamer** [comment] 2021-01-12 21:19
Hello! As this is very old, and we are unable to reproduce this (and are also unaware of its cause), we are going to close this.

**Closed by BomBardyGamer** 2021-01-12 21:19 UTC
Labels: bug
