### ISSUE TITLE
[BUG] Schematic version warn

### ISSUE THREAD

**Issue by DebuffPvP** [IridiumLLC/IridiumSkyblock#540] opened 2021-01-24 23:18 UTC
**Describe the bug**
I did /is regen and this issue on the gif happened lol

**Console Error**
[18:15:27 WARN]: [IridiumSkyblock] Failed to paste schematic using worldedit
[18:15:27 WARN]: [IridiumSkyblock] Tried to load a 1.13+ schematic in a native minecraft version

**Screenshots**
https://gyazo.com/2974fccaba087e842490e1902a0385fd

** Version **
This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by Faun471** [comment] 2021-01-27 06:19
> Tried to load a 1.13+ schematic in a native minecraft version

That already explains what the issue is. Use a schematic that is made on the correct version of minecraft. Using schematics for 1.13+ will not work for versions 1.12 and below. However, this *might* be a bug if you're using a schematic made on 1.8.8

**Comment by dlsf** [comment] 2021-02-02 12:53
I'd recommend you to join our support Discord if you need further support. As this is just a warning, I'll close this issue.

**Closed by dlsf** 2021-02-02 12:53 UTC
Labels: bug
