### ISSUE TITLE
[BUG] lava/water spill on a strange island

### ISSUE THREAD

**Issue by anticuatro** [IridiumLLC/IridiumSkyblock#519] opened 2021-01-14 22:06 UTC
Players can pouring **water and lava** on other people's Islands. This is done with a quick click, and players can also drain water and lava

I attach a video where the error is visible: [https://youtu.be/6je-B-nkBR8]

It would be great if you fixed this problem by allowing you to generate an island with the WorldGuard plugin, you can use the player's UUID for the region name, and it would also help to use WorldEdit

My data:
PaperSpigot 1.12.2
tested on Spigot 1.12.2 the problem remains

version plugin: latest 2.6.7
the bug also works in the past

**Comment by PeachesMLG** [comment] 2021-01-15 11:21
Duplicate of #497

**Closed by PeachesMLG** 2021-01-15 11:21 UTC
Labels: bug
