### ISSUE TITLE
[BUG] Iridium Skyblock duplicates valueBlocks in Islandmanager.json

### ISSUE THREAD

**Issue by Faun471** [IridiumLLC/IridiumSkyblock#232] opened 2020-08-17 02:37 UTC
**Describe the bug**
This is in the beta version pinned in the discord server. The plugin will disable because of a duplicated item in the islandmanager.json. It can be temporarily be fixed by removing the duplicated item then restarting the server. However, it will disable again after some time.

**To Reproduce**
1. Start your server using the beta version pinned in the discord server.
2. Wait until the plugin disables.
3. Find the error, [IridiumSkyblock] Failed to parse plugins\IridiumSkyblock\islandmanager.json: duplicate key: (The duplicated block)

**Islandmanager.json before and after the error**
I could not use hastebin/pastebin as the text is too long.

[Islandmananager.zip](https://github.com/IridiumLLC/IridiumSkyblock/files/5081871/Islandmananager.zip)

**Comment by donvdp** [comment] 2020-08-17 05:59
i have the exact same issue. is your dupe item also an IRON_BLOCK by chance ? :)

**Comment by Faun471** [comment] 2020-08-17 07:46
> is your dupe item also an IRON_BLOCK by chance ? :)

Sometimes. You can temporarily fix it:
1. Stop the server;
2. Remove the duplicated item in the islandmanager.json; and then
3. Start the server again.

**Comment by IridiumLLC** [comment] 2020-08-17 12:12
duplicate of #231

**Closed by IridiumLLC** 2020-08-17 12:12 UTC
Labels: bug
