### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Laotouy** [IridiumLLC/IridiumSkyblock#131] opened 2020-06-24 15:48 UTC
1. The trident can ignore the authority and cause damage to the island island members...
2. Standing on Shulker_Box and opening Shulker_Box will send a message of playersIslandIsPrivate
3. If the island is set to be private, members cannot use warp and go home
4. https://paste.ubuntu.com/p/yPYthpYF49/
      This error occurred when deleting the island and then entering the /is command to create the island
     The link above should be to click the delete island button in the menu, but the menu is loaded asynchronously and the 
     island is deleted before the loading is completed, so the above problem occurs
5. After the player dies, the resurrection will not show the border. The game version is 1.15.2, the world plugin is mv, and the server is spigot-1.15.2 
    It is recommended to send the border again after the player respawn

**Comment by IridiumLLC** [comment] 2020-06-24 16:10
1 and 3 should be fixed in the latest version. Number 2 is probably caused by another plugin, but it should also be fixed in latest version. Ill look into issue 4 and 5

**Closed** 2020-08-10 13:02 UTC
Labels: bug
