### ISSUE TITLE
[BUG] Infinite Money (vault) with Shift Click Depositing/Withdrawing Money

### ISSUE THREAD

**Issue by UPigmos** [IridiumLLC/IridiumSkyblock#177] opened 2020-07-12 18:36 UTC
Great plugin overall, 100% recommendThis is truly a great plugin, 

however there is one glitch that gave one of my players 50,000,000, and Unlimited in his is bank by Clicking under 0.5 Seconds in the IS Bank, it gave him money since I think the system didn't register, I tested it in other servers, and I am sure this is a Glitch with the plugin. Please fix this, and thank you.

**To Reproduce**
1. Go to a mc server with IridiumSkyblock installed
2. Click on is bank of /is (the menu)
3. Repeatedly Shift click with at least one space in your inventory, and have at least some money in your bank, and out of it

**Screenshots**
After Shift Clicking:

Couldn't re-create by myself, but the number was 57,543,265,34E

there was an E prob expressing exponents, making the dupe prob even worse

**Comment by UPigmos** [comment] 2020-07-12 18:37
Version is 1.15.2 By the way

**Comment by IridiumLLC** [comment] 2020-08-10 13:03
duplicate of #134

**Closed by IridiumLLC** 2020-08-10 13:03 UTC
Labels: bug
